import mandiri from '../assets/mandiri.png'
import mnc from '../assets/mnc.png'
import panin from '../assets/panin.png'
import commonwealth from '../assets/commonwealth.png'

const dataBank = [
    {
        id: 1,
        bank: 'mandiri',
        name: 'bunga special tengah imlek 2023',
        jaminan: [
            {id: 1, value: 'ruko'},
            {id: 2, value: 'rumah'},
            {id: 3, value: 'rukan'},
            {id: 4, value: 'apartemen'},
        ],
        target: [
            {id: 1, value: 'pengusaha'},
            {id: 2, value: 'karyawan'},
        ],
        komisi: 1,
        appraisal: 1,
        floating: 1,
        loanToValue: 1,
        penalty: 0,
        interestRate: 3.65,
        fixRatePercent: 3.65,
        fixRateYear: 3,
        maxTenor: 12,
        rating: 3,
        reviews: 10,
        users: 220,
        keterangan: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        url: 'none',
        img: mandiri
    },
    {
        id: 2,
        bank: 'panin',
        name: 'panin KPR & KPR XTRA',
        jaminan: [
            {id: 1, value: 'ruko'},
            {id: 2, value: 'rumah'},
            {id: 3, value: 'rukan'},
            {id: 4, value: 'apartemen'},
        ],
        target: [
            {id: 1, value: 'pengusaha'},
            {id: 2, value: 'karyawan'},
        ],
        komisi: 1,
        appraisal: 1,
        floating: 1,
        loanToValue: 1,
        penalty: 0,
        interestRate: 2,
        fixRatePercent: 3.65,
        fixRateYear: 3,
        maxTenor: 12,
        rating: 2,
        reviews: 24,
        users: 110,
        keterangan: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        url: 'none',
        img: panin
    },
    {
        id: 3,
        bank: 'mnc',
        name: 'MNC KPR Secondary',
        jaminan: [
            {id: 1, value: 'ruko'},
            {id: 2, value: 'rumah'},
            {id: 3, value: 'rukan'},
            {id: 4, value: 'apartemen'},
        ],
        target: [
            {id: 1, value: 'pengusaha'},
            {id: 2, value: 'karyawan'},
        ],
        komisi: 1,
        appraisal: 1,
        floating: 1,
        loanToValue: 1,
        penalty: 0,
        interestRate: 4.6,
        fixRatePercent: 3.65,
        fixRateYear: 3,
        maxTenor: 12,
        rating: 4,
        reviews: 55,
        users: 100,
        keterangan: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        url: 'none',
        img: mnc
    },
    {
        id: 4,
        bank: 'Commonwealth',
        name: 'KPR Primary',
        jaminan: [
            {id: 1, value: 'ruko'},
            {id: 2, value: 'rumah'},
            {id: 3, value: 'rukan'},
            {id: 4, value: 'apartemen'},
        ],
        target: [
            {id: 1, value: 'pengusaha'},
            {id: 2, value: 'karyawan'},
        ],
        komisi: 1,
        appraisal: 1,
        floating: 1,
        loanToValue: 1,
        penalty: 0,
        interestRate: 0,
        fixRatePercent: 3.65,
        fixRateYear: 3,
        maxTenor: 12,
        rating: 0,
        reviews: 0,
        users: 0,
        keterangan: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit ',
        url: 'none',
        img: commonwealth
    },
    {
        id: 5,
        bank: 'Commonwealth',
        name: 'KPR Primary',
        jaminan: [
            {id: 1, value: 'ruko'},
            {id: 2, value: 'rumah'},
            {id: 3, value: 'rukan'},
            {id: 4, value: 'apartemen'},
        ],
        target: [
            {id: 1, value: 'pengusaha'},
            {id: 2, value: 'karyawan'},
        ],
        komisi: 1,
        appraisal: 1,
        floating: 1,
        loanToValue: 1,
        penalty: 0,
        interestRate: 0,
        fixRatePercent: 3.65,
        fixRateYear: 3,
        maxTenor: 12,
        rating: 0,
        reviews: 0,
        users: 0,
        keterangan: '0 ',
        url: 'none',
        img: commonwealth
    },
];

export default dataBank